### ISSUE TITLE
3.3.0 test hangs on the linux_debian_10-gcc_10.1-static_O3 configuration

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/entt#2]
The `tests/basics/driver` runs for over 60min when built with GCC 10.1 `-std=c++2a -O3`.

**Comment by boris-kolpackov** [comment]
The same story with 3.3.1.

**Comment by boris-kolpackov** [comment]
And it seems to segfault in non-optimized build: https://cppget.org/entt/3.3.2/log/linux_debian_10-gcc_10.1/public/0.13.0/test

**Comment by boris-kolpackov** [comment]
The same story for 3.3.2. But 3.4.0 seems ok. Let me know if you would like to fix this. Alternatively, we can move 3.3.x to legacy. Here are all the relevant builds:

https://cppget.org/?builds=entt&cf=linux_debian_10-gcc_10.1*

**Comment by Klaim** [comment]
Thanks.

For me no problem moving that version to legacy, though that's because I'm assuming to be one of the few using this package (if not the only one at the moment) and I'm using the last version anyway.

Before that, I would like to point this issue to the library author in case they know about it.

**Comment by boris-kolpackov** [comment]
Ok, I've moved them to legacy for the time being (they we hanging our bots; we really need that test timeout support that you've suggested). Can move them back if there is a revision with the fix.

**Comment by Klaim** [comment]
The author agrees that it's not worth investigating so we can keep it in legacy.

**Comment by skypjack** [comment]
Also, feel free to ping me directly on GH next time. :wink: 
I'm more than willing to help, if possible. :+1:
